sudo: required
language: node_js
node_js:
- '6'
env:
  matrix:
  - provider=azure
  global:
  - azureSubId=384815d4-5dfc-42ca-ac21-e6230ef961fa
  - azureServicePrincipalTenantId=479263bf-f430-4f07-9d9f-35e9e3280de6
  - azureServicePrincipalClientId=http://azure-cli-2018-07-15-16-20-26
  - secure: r5bRepeZfP6TMJv6VMZfCpkHXXsfuqeoKoxnilxr0CavDmvfV54K4PbmUKBsPqGoU+1R/Y3bTheezyfvlqO0jK6GmesRIVQhCt9fqbPWB2jzWP7+2UgxKacZaP2YznJtFiX4enG2dUNBy1StVLqbUrJoPECpptkUAU2Am4l3EiDtxGyllOO6wHSbLddicV1FO41FAoVnU5/KKu3WNHW3xea/5njVYOEstXKUB1L+8DFpykXduGcBl0CpzLq8bfQYA9iEvWPDm45o51Dwqphq3esbZpe2R6dsGEdAvM5QWut8O35cog/x1wpfRs8EHsPUnVDNPnTLOfgTVDpx7gCsea5xjleT6qcMAkza+6Vg5Cnq64U80KmrYi0xuA5mgL/MEue89yJ4dafvG+CPXlK5N24OZ8lC34a3ResdRwlweZsMxYwTHs2LQ1MZn8qUBuw050krdbgr5aSD23EGZmr0bDGQpkxyU7zSNGUlVrc3B33nXihyDHPi48pLhD39PCy0wcM0eMxGGgvduzoX5RMgY3LP2jNJQ3SEJ+ZO+WJuc3/7vd53fJM3dFY8p0DJN99Pr4KxUS51k+kkx7bxgn8mBVF8VTGLcVVLSbtg6yQh3qJ6beWcA66FJuCpmIuce34Z+/eZL8rtlRqAg5G2bQZrDTDy9rn6z39vfJhTyTrX3EY=
  - secure: RFltXVSqJvM6254k44qCUTWv/lA3BkIhV90qvcNgCU+j3ErHT4MRrah30suhyJ2rjlFMxh0vfGzG8ACVj5XoRQsE4n5p0IL//e1gRLaPdLmB7fBmCp3jQRr+XSG+b1/9D7DxvQbt4K44DH9YPyWvSRSi0W6hGFWVfZtUHhmBJv2XP8M69Lu/RxDA13ZkoxZDPMq4SZ+ypvA4e63p1Bs9/bgMeiOK38H5bQXuaHJQ1re8lqNyeyZZBoa+cuWSIsSNqLz4VxMiuhZIu2M+g8Psw2TfKQrk6V0DTLHl2QojMRJukdzIhZFBRS7H6MXsPyo266EWzsqx41WfhywXMGyZLD6ErA7j6lEnSt62YeL74A8kTc/qQPqoX9BcE/P9egz74PaEo+R+Sf117S+A5M2STp/NYw3DenKENs5OmoAymKa3ntcw4bAHnJKt2UH2VXiO/JpJXDkgXKeHkT9OL9I5//WEjnt3AiQRJTWvNRL52JQgI2V8E8vh1BtXSV84svKXk9Edg66WRUiHncUZ6ao1bnPSXFv28Gdy0k/n8KWV3V36/gsPqrmNjV0hTNCbwSG2QCdc120beTr05whj8OCVQkjikHHBKygNtUncOrP/ooWopq8Ktn9Ux1rC0F70yNvMDEbuPlUfVp3JlRcSdMKws4nK+CDJdnGvPvVXwQ5uCJ8=
  - secure: iQFRIe4zWqv+NMbzb/5nutrkpdoPFEuGD7J39NhtETVHHeRKg1jn2JW6gDZHfkU4kNpqt/aHq+5pvn9rPassA7Xt96AHFq+/le8muFgCE6ogo0KfinzvunHfFjkUT/ywARcjGDn8vuxkuJDma+W2eX26vuAtUHRv0m384ZwNwFwyH5dHJoo/U0XSWt0XCoPFTlwoNrR/1hol6Lb46+Qhlzl6oNksovtNMXvwNy7ucFwAxqxrfaZoKjupbPXuzvMmovjIttay7fBQL2jHTNRG6C6Eq6joE0gxNX+fC8Rd0uZZZjglg2VOESrhjQ5DdXFe6m3WSQRfKaJM4+BJCLXS8MeByxVEA4gLWds6BmTEN5q70BCtKwsT8BsEAoahoZfRSJ37lp1/Z3qfgzTCXsJv391J+Opwiy4kB4jOdU5cFspyE4T43B5Zx1LKySi0/fIAznCwGzVK9iXVm2x/VGlhG8dSLEUGqFCP1Fh/uMxO3Da0niC4tDu0dgpAlCxbF6IGfZhzRCHtSQj8VFg0ORqThfIK7Eoj9iDV38M1JA7LJi7fSjCuDquEOLKmpVnAaeaw8nPzZj1tvMePrA09uRWtBCRytYA/jamMLJI6Pa/RnD8Zh/2kehsm49LGF1HLGH8Xxwjh8v5tGbENX0eFmtIId8aZdnL9z3x8J5/CmCtSZLk=
  - secure: RpSG0xaWLUxZ5td15XQ2tM4QS7qyAHR5HGDMNrcJn3Fo0wkTgN+MRUbFEu8VhuJvf70sAvj4APRMui2fJz7Cl7ITsyHS7FXyX8qTOQMAwYQZXYzAMRev1H85ab4O1ZK0zkD6tZPdtuEM7a3MFwB0w+M/8x7Ov++o/oyMdl60NkftbikgakNE31lOT7EqQZ7PIiP9hQP6dWah2xKAkgCo7IbABd4XkTwbKyiA6/ZMm5hzrDGy3WaryV1VTJhsi6TohIn6W7bTAZ9XfiNR2voDI6HWRt+4hj2iFCWDhNevjcXvgWeOuOuzBEyI9iVEd4IUeRlB4BAl2xD98aYFoHyGNs0uRgnoo2eq0LOvYX6ogSoqJda63DwIooyMbirss1w2xQ5WNEoY3FpcesKIfAYsb8qoyvNygRTJlpkIGD7aN6q3px4fDaHmx5I7TR8toz2edT7c+oRuTZQJSCftscYqyT61ZQB2/LpHBQgmsIpGF3R71aYAsgImcveQMzpFsRy/WpsbkPM7EAuCUyIUhG4pVPZyABUiOL7/yqLy29wJtI69UUFrG4HxOGyz0s94FcZW85bEIQ4KMVEfVTEPNG2sp04OBO8GlhhI5P9yOrsebm09WQTjhsNabaKzqfeDy5q1LAojJ0PbYNehbSJeEXBJF4iG6qRYBnfq9z2gpsGxNqY=
before_install:
- sudo apt-get install libsecret-1-dev
- npm install -g serverless
- echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release
  -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
- curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
- sudo apt-get install apt-transport-https
- sudo apt-get update && sudo apt-get install azure-cli
- cd packages/azure
install:
- yarn install
before_script:
- echo $AZURE_USERNAME
- echo $AZURE_PASSWORD
- echo $PROVIDER
- echo $provider
- echo $azureUsername
- echo $azurePassword
- echo $azureSubId
- echo $azureServicePrincipalTenantId
- echo $azureServicePrincipalClientId
- az login -u $azureUsername -p $azurePassword
jobs:
  include:
  - stage: build
    name: Deploy Test
    script: yarn deploy:test
    env:
    - secure: GRFSiS9JmjxAvR7f+QHgHCZ9KwjfqXwz0RFjA47GknAShxL4eNyQ70xok0v9H5+d1MMRrZXXdZmdVfs4KN14wmtF53AQ2Dwu61QyLut2n4jOxwD+PM8QxVlN/o70SHUulca6QVa9lE6bHpHuiWgHPex1YyYwSTKCiYTXctsuuP/fO0ifQlqrXIogJ4EfVwmIx1TdToYoD/4mLIYsrUAKonw8rm2mSvX+1/ynKeoIsFZG7iStObaSITY7aaM99LjJADNZRF0ucvgIncyi2Eno/OjC85a6XrLIbpMn/O7TUo+RQC5x8SFKjAOG/53dvYLyOCGwNgoQr0yYxLHZNvDn3ftZCYuTYMbs69FiNLuoDbirRSx8wQjzIeUePlfS9gtGQfEOeUMvuRnhT4yx0Xqt9qQ4LCfVfNFF1dr8Vn1cTMYN/gB+b6dzh53Xbw3ILoSrnUFp/m9mXdI0k1yX3CYHIP2jR/kQVA7jFQMiAalqxyRpDXBm6da7VZDjYJ9aODqJqu/1h8YhUOGhuwhho2lJKPxeXYYz04Eybg++KuX48zi/3HnZzsu+9NOUhiBYfY1YXbyFHA261eo70ohwbklEeF4ok4l4RebXegdvM6hWxv0vJih8RZAr9VbQV9CAHEcnr23sd6oGHeKSqbQNfDYAk9ml+tIhPjf7B1RTUtj+I0g=
  - stage: test
    name: Tests
    script: yarn test
  - stage: deploy
    if: branch = master
    name: Deploy
    script: yarn deploy:prod
    env:
    - secure: jdszRnnYyOLCRpDpVfXMM0w8pQyQYixnCJQdHqA/DYtBncJc5j1qTrxQjp4f4hiXaQyijhOWq7BZ6M0B2QbxoL064/bkVlhZpKUufxz6gZHvWkI20YOpCFVKUSt+PRGTgBKynumE2ecv9AxJxU0yNUiZ9zkBL8GxuKyLMB1e15t5QdwtvlUKa7Vtz+dHpd45vVqUkNTRUP0y0nCnhC9cW+6jjuFx//dVSG5Durp7SqViWV2kIEeSi09WXZ1N4roGvttvX4Y32YvWxyGMSFlEssBJRS3aWwjg8unRhSseZnfddCWK0/MfVyaDPk72ZoK7h6WYubQz5vXFAX2g9Vi9pJcCP+skK/J3gRTXXYg+YUlHpPSNNbMQ5m/yze+CTY96IhaFUFwFKMyquA4MSuj3F784aDDDwHcYNqS4/CqsvB3kIeJX6zuq/Uu+1hkCVjXJ1YkhPAHFLLSaSjJOkTX1dSMda8Sbsy79d6bxUZClqQB61IMPZKPYpsvQVqmN6sqsauT6JHajqpcqjQju5RYxhjm3r2CwK9A84h7cXtI0BECevpjsdteU6dJz4HkIkZjsdWFIVnX5gar9oTSdXgQepF7NRdpYLbzvrVtLq3lBa9MTBmqGJwTfJjDkqP2T1O5rnW5CNoMg0FVzZQMIbhhNbx7/Plc3WXlqr8bvuxhsFkI=
