service: ${self:custom.config.service}-hello-v7

provider:
  name: openwhisk
  timeout: 240
  stage: dev

plugins:
  - serverless-openwhisk
  - serverless-plugin-write-env-vars

custom:
  config: ${file(../../config/index.js)}
  stage: ${self:custom.config.stage}
  writeEnvVars:
    stage: ${self:custom.stage}
    inputBucket: ${self:custom.config.inputBucket}
    bucket: ${self:custom.config.bucket}
    storageEndpoint: ${self:custom.config.storageEndpoint}
    authEndpoint: ${self:custom.config.authEndpoint}
    apiKeyId: ${self:custom.config.apiKeyId}
    serviceInstanceId: ${self:custom.config.serviceInstanceId}

functions:
  hello:
    handler: hello.handler
    memory: 256
    events:
      - http: POST hello
