service: ${self:custom.service}

provider:
  name: azure
  location: westeurope

plugins:
  - serverless-azure-functions

custom: ${file(./environment/environment.js)}

functions:
  transfer:
    handler: handler.transfer
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          diections: out
          name: res
