service: ${self:custom.config.service}

provider:
  name: azure
  location: westeurope
  stage: dev

plugins:
  - serverless-azure-functions
  - serverless-plugin-write-env-vars

custom:
  config: ${file(./config/index.js)}
  stage: ${self:custom.config.stage}
  writeEnvVars:
    stage: ${self:custom.stage}
    connectionString: ${self:custom.config.connectionString}
    inputContainer: ${self:custom.config.inputContainer}
    container: ${self:custom.config.container}

functions:
  transfer:
    handler: handler.transfer
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          diections: out
          name: res

package:
  exclude:
    - .git/**
    - .gitignore
    - README.md
    - .serverless.env
    - config/**
  include:
    - handler.js
    - node_modules/**
    - config/custom-environment-variables.yml
    - config/default.yml
    - config/${self:custom.stage}.yml
    - config/dev.yml
    - config/index.js
    - .env
